apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv 
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/storage/postgresql
    server: 10.107.85.103

